SELECT CONCAT(NAME,CONCAT("(",SUBSTRING(OCCUPATION,1,1),")")) FROM OCCUPATIONS
ORDER BY NAME;
SELECT "There are a total of ",COUNT(*)," ",CONCAT(LOWER(OCCUPATION),"s.")
FROM OCCUPATIONS 
GROUP BY OCCUPATION
ORDER BY COUNT(*);
-- SELECT * FROM OCCUPATIONS



